trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

stages:
- stage: Provision
  jobs:
  - job: provision_azure_infrastructure
    displayName: Provision Azure Infrastructure
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: DownloadSecureFile@1
      name: DownloadTerraformTfvars
      displayName: Download terraform.tvars
      inputs:
        secureFile: 'terraform.tvars' 